# Generated by Django 4.0.6 on 2022-07-06 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Клиент')),
                ('device_type', models.CharField(max_length=200, verbose_name='Тип устройства')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('defect', models.TextField(verbose_name='Заявленная неисправность')),
                ('completed_work_text', models.TextField(verbose_name='Проделанная работа')),
                ('spare_parts_text', models.TextField(verbose_name='Закупленные запчасти')),
                ('income', models.IntegerField(verbose_name='Приход')),
                ('consumption', models.IntegerField(verbose_name='Расход')),
                ('total', models.IntegerField(verbose_name='Итого')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания работ')),
                ('master_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
        ),
        migrations.CreateModel(
            name='Spare_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Наименование запчасти')),
                ('price', models.IntegerField(verbose_name='Стоимость запчасти')),
                ('part_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helperserver.order')),
            ],
        ),
        migrations.CreateModel(
            name='Complited_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Название работы')),
                ('price', models.IntegerField(verbose_name='Стоимость работы')),
                ('order_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helperserver.order')),
            ],
        ),
    ]
