# Generated by Django 4.0.6 on 2022-07-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helperserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed_work_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spare_parts_text',
        ),
    ]
