# Generated by Django 4.0.6 on 2022-07-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helperserver', '0004_rename_part_spare_parts_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Complited_work',
            new_name='Work',
        ),
    ]
