# Generated by Django 4.0.6 on 2022-07-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helperserver', '0005_rename_complited_work_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spare_parts',
            new_name='Spare_part',
        ),
        migrations.RemoveField(
            model_name='order',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='order',
            name='defect',
        ),
        migrations.RemoveField(
            model_name='order',
            name='income',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Время поступления денег')),
                ('amount', models.IntegerField(verbose_name='Поступленные средства')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helperserver.order')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание дефекта')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helperserver.order')),
            ],
        ),
    ]
